server:
  port: 8080

spring:
  application:
    name: citynature
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/citynature
    username: root
    password: ltr19980723
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  web:
#    resources:
#      static-locations: /static/static/


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml #mapper的映射文件路径
  type-aliases-package: com.flyhigh.citynature.domain
#config-location: #指定mybatis核心配置文件

